# Método where()

Este método permite que você selecione valores de um array com base em uma condição, ou que substitua valores com base nessa condição.

Este método tem a seguinte estrutura:

np.where(condição, valor_se_verdadeiro, valor_se_falso)

Link documentação: https://numpy.org/doc/stable/reference/generated/numpy.where.html

## Exemplo 1)

In [1]:
import numpy as np

# criando array numpy de 0 a 9
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
# np.where(condição, valor_se_verdadeiro, valor_se_falso)
np.where(a<5,a,a*10)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

## Exemplo 2)

In [3]:
np.where([[True, False], [True, True]],
         [[1, 2], [3, 4]],
         [[9, 8], [7, 6]])

array([[1, 8],
       [3, 4]])

Posição (0,0): Condição é True → pega 1 (de [[1, 2], [3, 4]]).

Posição (0,1): Condição é False → pega 8 (de [[9, 8], [7, 6]]).

Posição (1,0): Condição é True → pega 3 (de [[1, 2], [3, 4]]).

Posição (1,1): Condição é True → pega 4 (de [[1, 2], [3, 4]]).

Resultado:

array([[1, 8],
       
       [3, 4]])

## Exemplo 3) Encontrando índices onde a condição é verdadeira

O método where() irá retornar o índices do array onde a condição dada no método for verdadeira

In [4]:
arr = np.arange(10,60,10)
arr

array([10, 20, 30, 40, 50])

In [5]:
indices = np.where(arr>30)
indices

(array([3, 4], dtype=int64),)

## Exemplo 4) Substituindo valores com base em uma condição

Se o valor for maior que 30, substituímos 1, caso contrário, por 0

In [6]:
np.where(arr>30,1,0)

array([0, 0, 0, 1, 1])

# Exercícios (13/09/2024)

## Exercício 1) Substituir valores negativos por zero

Dado um array de números inteiros, use np.where() para substituir todos os valores negativos por zero, mantendo os valores positivos inalterados.

In [7]:
a = np.arange(-10,10,2)
a

array([-10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8])

In [8]:
np.where(a < 0, 0, a)

array([0, 0, 0, 0, 0, 0, 2, 4, 6, 8])

## Exercício 2) Classificar valores com base em uma condição

Crie um array de números aleatórios entre 0 e 100. Usando np.where(), classifique os valores em duas categorias:

* "Alta" se o valor for maior ou igual a 50.

* "Baixa" se o valor for menor que 50.

In [16]:
np.random.seed(42)
num = np.random.randint(100, size=10)
num

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

In [17]:
np.where(num > 50, 'Alta', 'Baixa')

array(['Alta', 'Alta', 'Baixa', 'Alta', 'Alta', 'Baixa', 'Alta', 'Alta',
       'Alta', 'Alta'], dtype='<U5')

## Exercício 3) Substituir valores pares por seu dobro

Dado um array de números inteiros, use np.where() para dobrar o valor de todos os números pares e deixar os números ímpares inalterados.

In [19]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.where(b%2 == 0, 2*b, b)

array([ 0,  1,  4,  3,  8,  5, 12,  7, 16,  9])

## Exercício 4) Substituir valores em uma matriz

Dada uma matriz 3x3 de números aleatórios entre 1 e 10, use np.where() para substituir todos os valores maiores que 5 por 1 e os demais por 0.

In [31]:
np.random.seed(42)
c = np.random.randint(1,11, size=(3,3))
c

array([[ 7,  4,  8],
       [ 5,  7, 10],
       [ 3,  7,  8]])

In [32]:
np.where(c > 5, 1, 0)

array([[1, 0, 1],
       [0, 1, 1],
       [0, 1, 1]])

## Exercício 5) Calcular a média e substituir valores abaixo da média

Crie um array de números inteiros e calcule a média. Usando np.where(), substitua todos os valores abaixo da média pela própria média.


In [39]:
np.random.seed(42)
d = np.random.randint(20, size=10)
print(d)
print(np.mean(d))

[ 6 19 14 10  7  6 18 10 10  3]
10.3


In [40]:
np.where(d < np.mean(d), np.mean(d), d)

array([10.3, 19. , 14. , 10.3, 10.3, 10.3, 18. , 10.3, 10.3, 10.3])